version: '3.7'
services:

  mysql:
    image: mysql
    container_name: office-mysql
    restart: on-failure
    volumes:
      - ./volumes/db/data:/var/lib/mysql
    ports:
      - 9001:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: office
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    networks:
      - net
      - logging-net

  api:
    container_name: office-api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./volumes/conf:/usr/src/office/resources
    ports:
      - 8001:8080
    logging:
      driver: gelf
      options:
        gelf-address: "udp://logstash:12201"
        tag: "intouch-api"
    networks:
      - net
      - logging-net
    depends_on:
      - mysql

networks:
  net:
  logging-net:
    external:
      name: logging-net