version: '3.7'
services:
  mysql:
    image: mysql
    #container_name: office-mysql
    restart: on-failure
    volumes:
      - ./volumes/db/data:/var/lib/mysql
    ports:
      - 9001:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: office
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    networks:
      - net
      - logging-net

  api:
    image: punk91/office:1.1
    #container_name: office-api
    volumes:
      - ./volumes/conf:/usr/src/office/resources
    ports:
      - 8080:8080
    networks:
      - net
      - logging-net
    depends_on:
      - mysql

networks:
  net:
  logging-net:
    external: 
      name: logging-net

